### ISSUE TITLE
The parameter "adj_mat_time_window" cannot be set to None.

### ISSUE THREAD

**Issue by maxmustermann123** [IBM/EvolveGCN#18]
When setting the parameter `adj_mat_time_window: None` in the parameters_example.yaml file, the experiment crashes with the error:

`Traceback (most recent call last):
  File "/evolveGCN/run_exp.py", line 220, in <module>
    tasker = build_tasker(args,dataset)
  File "/evolveGCN/run_exp.py", line 122, in build_tasker
    return lpt.Link_Pred_Tasker(args,dataset)
  File "/evolveGCN/link_pred_tasker.py", line 38, in __init__
    self.get_node_feats = self.build_get_node_feats(args,dataset)
  File "/evolveGCN/link_pred_tasker.py", line 98, in build_get_node_feats
    max_deg,_ = tu.get_max_degs(args,dataset)
  File "/evolveGCN/taskers_utils.py", line 60, in get_max_degs
    cur_adj = get_sp_adj(edges = dataset.edges,
  File "/evolveGCN/taskers_utils.py", line 96, in get_sp_adj
    subset = subset * (idx[:,ECOLS.time] > (time - time_window))
TypeError: unsupported operand type(s) for -: 'int' and 'str'`

The explanation from the same file is: "# Time window to create the adj matrix for each timestep. Use **None to use all the history** (from 0 to t)". Is there another way to use all the history from 0 to t?

**Comment by NikhilT-DS** [comment]
Maybe you can comment out line number 96 in taskers_utils.py
`    subset = subset * (idx[:,ECOLS.time] > (time - time_window))`
